### ISSUE TITLE
Página de pesquisa

### ISSUE THREAD

**Issue by oigabrielteodoro** [L4T1NN0/github-explorer#1]
### Tasks
- [x] Estilização da página
- [x] Estrutura da página html
- [x] Integração com o Github API
