### ISSUE TITLE
Página de pesquisa de repositórios

### ISSUE THREAD

**Issue by oigabrielteodoro** [L4T1NN0/github-explorer#2]
### Tasks
- [x] Estrutura da página html
- [x] Estilização da página
- [ ] Integração com o Github API
